### ISSUE TITLE
Migrate theme to new storefront version with Scriban view engine

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-theme-default#79]
The primary  objective is allow to run the vc-theme-default with the new storefront that powered by new Scriban, end-user liquid template engine

**Technical details:**
- The new storefront version with Scriban engine can be taken from this branch https://github.com/VirtoCommerce/vc-storefront-core/tree/features/scriban-migration

- All theme changes should be performed  in special   branch `scriban-migration`  in GitHub repository of this theme

- All known breaking changes related with  new theme syntax  are described in this issue https://github.com/VirtoCommerce/vc-storefront-core/issues/188

- The list of e2e tests that's the new theme must pass
[e2e tests.zip](https://github.com/VirtoCommerce/vc-theme-default/files/3042624/e2e.tests.zip)

**Comment by ilyawzrd** [comment]
@tatarincev, i made a commit  https://github.com/VirtoCommerce/vc-theme-default/commit/1e1c422f3e378e38140cdf64a8ae351636218072 to branch with scriban theme and also made a comment https://github.com/VirtoCommerce/vc-storefront-core/issues/188#issuecomment-484913658 about syntax change,but still have few problems here:

1) Can't show "Sign in/Create an account" links. I guess it's because of property "shop.customer_accounts_enabled", but i can't find it
https://github.com/VirtoCommerce/vc-theme-default/blob/1e1c422f3e378e38140cdf64a8ae351636218072/layout/account_layout.liquid#L80

2) Same as 1) 
https://github.com/VirtoCommerce/vc-theme-default/blob/1e1c422f3e378e38140cdf64a8ae351636218072/layout/theme.liquid#L90

3) It shows an error that something wrong with "For" loop. 
![List-collections](https://user-images.githubusercontent.com/22875828/56427733-36d85900-62bd-11e9-81d5-fa10c641a9fc.png)
https://github.com/VirtoCommerce/vc-theme-default/blob/1e1c422f3e378e38140cdf64a8ae351636218072/templates/list-collections.liquid#L6

4) allVariationPropsMap is a variable from assets/js/product.js, but function getFlatternDistinctPropertiesMap returns empty object when i debug it. I think it can be something with dependency script locally,because in old version of theme i have the same result without showing props.
https://github.com/VirtoCommerce/vc-theme-default/blob/1e1c422f3e378e38140cdf64a8ae351636218072/templates/product.liquid#L119
https://github.com/VirtoCommerce/vc-theme-default/blob/1e1c422f3e378e38140cdf64a8ae351636218072/assets/js/product.js#L75

5) "For" loop is not working. 
https://github.com/VirtoCommerce/vc-theme-default/blob/1e1c422f3e378e38140cdf64a8ae351636218072/snippets/collection-sidebar.liquid#L4

6) Images and prices for products are not showing
https://github.com/VirtoCommerce/vc-theme-default/blob/1e1c422f3e378e38140cdf64a8ae351636218072/snippets/product-list-item.liquid#L29

**Comment by trueboroda** [comment]
A new problem has been found. When you use site search an error occurs.
![image](https://user-images.githubusercontent.com/13153256/58072915-d7b28080-7ba9-11e9-947d-2b18c6394f27.png)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v2.0.0
